'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CORE_PER_PEN_ALI

    '''<summary>
    '''txt_nombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nombre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FilteredTextBoxExtender_nombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender_nombre As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''txt_RFC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_RFC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_busca_usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_busca_usuario As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_eliminarB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_eliminarB As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_estatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_estatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_nueva_pea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_nueva_pea As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_calcular_pen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_calcular_pen As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_descargar_pen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_descargar_pen As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvw_pensiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvw_pensiones As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnl_modal_confirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_modal_confirmar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btn_confirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_confirmar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_cancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancelar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''modal_confirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modal_confirmar As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''hdn_alertas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_alertas As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
